* Spending
** 2016
The credit card report says: 14027.62

However, some of that money was company travel related and was later
reimbursed. Looks like ~2000 was company related travel so the real
amount spent was ~12000

In 2016 I also paid 1270 per month for rent.

Totalling that all up means that this year I spent about:
(+ (* 1270 12) 12000) = 27240

** 2017
The credit card report says: 16052.77. The 2 contributors to that
increase seem to be ~600 from when I bought a lot of transit stuff
when I was home and travelling to NYC a lot. My mon reimbursed me for
most of that though so maybe I actually spent more or less the same
total amount as last year. Minus the restaurants though which I
increased spending on a whopping ~1700 more.

However, some of that money was company travel related and was later
reimbursed. Looks like ~1600 was company related travel so the real
amount spent was ~14400

In 2017 I again paid 1270 per month for rent.

Totalling that up means I spent about:
(+ 14400 (* 12 1270)) = 29640

I tried to get a more accurate number by just subtracting the
subtracting the checking account debit from the credit. Unfortunately
it seems a little messy to do because they'll count things like
transferring amounts to savings as a debit.

Totalling up the creids though I made 49406.2 in 2017 which means I
made:

(- 49406.20 29640.00) = 19766.20

So the percentage of my income that I was able to save that year was:

(* 100 (/ 19766.20 49406)) = 40%

* Milestones
** Financial Security
You're *needs* are completely covered by your investments for the rest
of your life. So things like:
- mortgage/rent
- utilities
- food
- basic transportation needs
- basic insurance costs

Its tough to estimate all this stuff because so much of my food
spending is tied up with paying for Ara. Additionally I would probably
be spending less on basic transportation because normally I only
travel when going out to eat. Also, I'm not sure how much more I would
need to spend at a grocery store to eliminate needing to go to
restaurants. I'm estimating that ~1 in groceries == ~4 in restaurants:

In 2016 I would estimate my financial needs at:
- rent: 15240
- utilities: 1000
- food: 2900
- basic transportation needs: 300 (adding up ventra purchases)
- insurance: 1320

Which totals to 20760

In 2017 I would estimate my financial needs at:
- rent: 15240
- utilities: 500 (RCN started charging $1 per month)
- food: 3294
- basic transportation needs: 400 (guess I travelled more this year!)
- insurance: 1320

Which totals to 20754

I guess the thing about "needs" is that they shouldn't change too much
from year to year. Not sure how *exactly* accurate this number is (for
instance I think my insurance is cheaper because of getting it through
my company) but its a good place to start.

So to acheieve the milestone of financial security I will need $20000
per year.

Rent is taking up a whopping ~75% of my needs. It was that high
because I was paying Ara's portion *but* Zach, for example, paid more
than me in rent so its not an unrealistic figure to see. That being
said, I feel like I could (and should) try to shave off ~5000 (which
means a monthly reduction of 416) if I really tried which would put my
financial security amount at $15000.

And now that Ara is going to start paying her portion of the rent,
which shaves off $600, that $15000 figure seems a lot more reasonable
at least for the time being. Since I'll also start saving more in my
day-to-day shopping (by doing things like shopping at costco) I'm just
gonna split the difference and put my financial security number at
$17500 per year.

You know what. Actually, I'm gonna just gonna set 2 goals:
1. Soft financial security amount - 15000
2. Official financial security amount - 20000

** Financial Vitality
This number would be halfway between financial security and financial
independence which would mean 25000 for me.

** Financial Independence
Looking spending for 2016 and 2017 it would appear that financial
independence will be reached when my yearly income from investments
is 30000.

** Financial Freedom
The ability to splurge and not hurt your financial independence. The
book says 2-3 significant luxuries and I think they mean that you only
get 2-3 for the rest of your life. For instance buy 2-3 more houses
(or something like that) and not have t owork for them. A smaller
luxury would be taking an extra vacation per year. Or maybe I would
like to be able to purchase more DVC stuff. Who knows!

I would like financial freedom because if I do not have it then my
finances are somewhat locked in for the rest of my life. My lifestyle
is now kind of locked in to some extent. Sure I could revert to living
off just what I need to get the extra cash but I'd rather not. This
extra cash would also, I imagine, serve as a bit of a buffer in case
something goes wrong. I also really like the idea of being able to
donate some of my money.

I imagine that if I had some extra money I'd like to either:
- keep saving it so my money machine will continue to make *more* as
  time goes on
- take an extra vacation or 2 every year
- donate
- eventually I would consider purchasing something big like a house
- giving money to friends or family

I have no idea how much some of those would cost but the amount $50000
per year sounds rather nice to me. I'll have goals in increments
of 10. So my financial freedom goals are: 40000 then 50000.

** Absolute Financial Freedom
The power to do, more or less, anything you want whenever you want. I
cannot imagine getting to this level and even if I did I'm not sure
what I would do.

But if I did ever reach this point then I picture doing something
education related. For example I have this image in my mind of
teaching a computer programming class and giving every student a tiny
linux laptop similar to what Wyatt had. Computer literacy feels like a
very important subject to me. Even if you have only a passing
understanding it will help greatly in thinking logically. Or perhaps I
would teach some sort of investing class and give them 1000 dollars to
invest however they want. Something to do with education and learning
though.

* Goals
"I've found that if you try to figure out a percentage to save without
really knowing what you're saving for, it's not going to happen. The
secret is to know what you truly want and why you want it, and make it
a burning passion. Suddenly your creativity will be unleashed, and
you'll find new ways to earn more, to save more, to add more value, to
become more tax efficient, to become a better investor, or to make a
lifestyle change that improves your life and gives you some of your
dreams today, and not in the future. That's the key to it all"

What I primarily want from investing/saving is more time.

Why I want more time is because I only get one life as far as I know
so I want to spend as much time as possible doing things that are
meaningful to me. I'm not sure *exactly* what I will do with the extra
time but I'll have more time to figure that out so I'm not too
worried :).

""
